### ISSUE TITLE
slowmode.py:54 - __new__() got an unexpected keyword argument 'allow_new'

### ISSUE THREAD

**Issue by aquova** [aquova/governor#11]
A large number of exceptions in slowmode were raised with the error: '__new__() got an unexpected keyword argument 'allow_new''. Found this non-English article online that implies it is due to audit log settings. Need to investigate further.

https://tmrtkr.tistory.com/67

**Comment by reecebenson** [comment]
_(Found this issue on Google as I was having the same issue)._
You can resolve this issue by updating the `discord.py` library to its latest version:
```
python -m pip install -U discord.py
```
Hope that helps!

**Edit:** I've raised a PR (#12) to resolve this issue for you.
