### ISSUE TITLE
Thoughts on Adding DM Listeners?

### ISSUE THREAD

**Issue by andyruwruw** [aquova/governor#14]
Would be nice to be able to send commands to Mr. Governer directly, but I can understand he feels uncomfortable handing out his personal number for business.

**Comment by aquova** [comment]
I'm going to be honest, I never really considered giving Governor the ability to respond to users in DMs. It actually seemed to work pretty well up until now, but I've recently removed the ability for it to respond, as we didn't want people using DMs to grind for server XP points. For now, I think we'll keep it where the bot will only respond in chat, however I would be open to allowing command responses in DMs if there is enough interest.

**Comment by andyruwruw** [comment]
Oh yeah, I didn't mean DMs could add XP, just DM as a place to test and use commands. But understandable.
